# HW 9
___

In [1]:
import numpy as np

### Spelling Correction
Suppose you type `blder` into a search engine. It will try to match your entry to common search terms. Perhaps you actually meant to type `boulder` or `bold` or `baller`. The search engine might guess the word you intended by calculating the fewest number of changes needed to convert your entry into a common search term. It can then ask 'Did you mean ...?'. For example, the calculations would find that

* To convert `blder` into `boulder`, one can insert `o` and `u`, a total of 2 changes.
* To convert `blder` into `bold`, one can insert `o` and omit `e` and `r`, a total of 3 changes.
* To convert `blder` into `baller`, one can insert `a`, replace `d` with `l`, a total of 2 changes.

Use dynamic programming to write a function **`string_convert(str1, str2)`** that takes two strings `str1` and `str2` and returns the minimum number of changes needed to convert `str1` to `str2` using the following operations:
* **insert** which adds a character from `str2` to `str1`
* **omit** which omits a character from `str1`
* **replace** which replaces a character in `str1` with a character in `str2`
* **`match`** which does not entail any changes. 

The function also should print the operations that correspond to the minimum number of changes.

Example:<br>
`string_convert('bffflooo', 'buffalo')` might print
```
match   b
replace u
match   f
match   f
insert  a
match   l
match   o
omit    o
omit    o
```
and return `4`. There are other solutions with 4 moves.

In [16]:
str1 = 'bffflooo'
str2 = 'buffalo'

In [17]:
m = len(str1)
n = len(str2)


# initialize matrices of the right sizes
zeros = [0]*(n+1)
c1 = np.array([zeros for _ in range(m+1)])
b1 = np.array([zeros for _ in range(m+1)])


# populate the two matrices
for i in range(m+1):
    c1[i,0] = i
for j in range(n+1):
    c1[0,j] = j

for i in range(1, m+1):
    for j in range(1, n+1):
        if str1[i-1] == str2[j-1]:      #MATCH
            c1[i, j] = c1[i-1,j-1]
            b1[i, j] = 4 #'NWArrow_Match'

        elif c1[i-1,j] == c1[i,j-1]:       #REPLACE
            c1[i, j] = c1[i-1,j-1] + 1
            b1[i, j] = 3 #'NWArrow_Replace'

        elif c1[i-1,j] < c1[i,j-1]:      #OMIT
            c1[i,j] = c1[i-1,j] + 1
            b1[i,j] = 2 #'UpArrow'

        else:                          #INSERT
            c1[i,j] = c1[i,j-1] + 1
            b1[i,j] = 1 #'LeftArrow'

In [18]:
b1

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 4, 1, 1, 1, 1, 1, 1],
       [0, 2, 3, 4, 4, 1, 1, 1],
       [0, 2, 2, 4, 4, 1, 1, 1],
       [0, 2, 2, 4, 4, 1, 1, 1],
       [0, 2, 2, 2, 2, 3, 4, 1],
       [0, 2, 2, 2, 2, 2, 2, 4],
       [0, 2, 2, 2, 2, 2, 2, 4],
       [0, 2, 2, 2, 2, 2, 2, 4]])

In [19]:
m = len(str1)
n = len(str2)


# initialize matrices of the right sizes
zeros = [0]*(n+1)
c = np.array([zeros for _ in range(m+1)])
b = np.array([zeros for _ in range(m+1)])


# populate the two matrices
for i in range(m+1):
    c[i,0] = i
for j in range(n+1):
    c[0,j] = j

for i in range(1, m+1):
    for j in range(1, n+1):
        if str1[i-1] == str2[j-1]:      #MATCH
            c[i, j] = c[i-1,j-1]
            b[i, j] = 4 #'NWArrow_Match'

        elif i == j:       #REPLACE
            c[i, j] = c[i-1,j-1] + 1
            b[i, j] = 3 #'NWArrow_Replace'

        elif i > j:      #OMIT
            c[i,j] = c[i-1,j] + 1
            b[i,j] = 2 #'UpArrow'

        else:                          #INSERT
            c[i,j] = c[i,j-1] + 1
            b[i,j] = 1 #'LeftArrow'

In [20]:
b

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 4, 1, 1, 1, 1, 1, 1],
       [0, 2, 3, 4, 4, 1, 1, 1],
       [0, 2, 2, 4, 4, 1, 1, 1],
       [0, 2, 2, 4, 4, 1, 1, 1],
       [0, 2, 2, 2, 2, 3, 4, 1],
       [0, 2, 2, 2, 2, 2, 3, 4],
       [0, 2, 2, 2, 2, 2, 2, 4],
       [0, 2, 2, 2, 2, 2, 2, 4]])

In [12]:
b==b1

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True, False,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

In [13]:
def print_changes(b, str1, str2, i, j):
    if i==0 or j==0:
        return None
    if b[i,j] == 4:                 #'NWArrow_Match'
        print_changes(b, str1, str2, i-1, j-1)
        print(f'match    {str1[i-1]}')

    elif b[i,j] == 3:               #'NWArrow_Replace'
        print_changes(b, str1, str2, i-1, j-1)
        print(f'replace  {str2[j-1]}')

    elif b[i,j] == 2:               #'UpArrow'
        print_changes(b, str1, str2, i-1, j)
        print(f'omit     {str1[i-1]}')

    else:                           #'LeftArrow'
        print_changes(b, str1, str2, i, j-1)
        print(f'insert   {str2[j-1]}')

In [14]:
print_changes(b1, 'bffflooo', 'buffalo', 8, 7)

match    b
replace  u
match    f
match    f
insert   a
match    l
omit     o
omit     o
match    o


In [21]:
c1[8,7]

4

In [22]:
print_changes(b, 'bffflooo', 'buffalo', 8, 7)

match    b
replace  u
match    f
match    f
replace  a
replace  l
omit     o
match    o


In [23]:
c[8,7]

4

### String Convert Function

In [174]:
def string_convert(str1, str2):
    m = len(str1)
    n = len(str2)


    # initialize matrices of the right sizes
    zeros = [0]*(n+1)
    c = np.array([zeros for _ in range(m+1)])
    b = np.array([zeros for _ in range(m+1)])


    # populate the two matrices
    for i in range(m+1):
        c[i,0] = i
    for j in range(n+1):
        c[0,j] = j

    for i in range(1, m+1):
        for j in range(1, n+1):
            if str1[i-1] == str2[j-1]:      #MATCH
                c[i, j] = c[i-1,j-1]
                b[i, j] = 4 #'NWArrow_Match'

            elif c[i-1,j] == c[i,j-1]:       #REPLACE
                c[i, j] = c[i-1,j-1] + 1
                b[i, j] = 3 #'NWArrow_Replace'

            elif c[i-1,j] < c[i,j-1]:      #OMIT
                c[i,j] = c[i-1,j] + 1
                b[i,j] = 2 #'UpArrow'

            else:                          #INSERT
                c[i,j] = c[i,j-1] + 1
                b[i,j] = 1 #'LeftArrow'


        def print_changes(b, str1, str2, i, j):
            if i==0 or j==0:
                return None
            if b[i,j] == 4:                 #'NWArrow_Match'
                print_changes(b, str1, str2, i-1, j-1)
                print(f'match    {str1[i-1]}')

            elif b[i,j] == 3:               #'NWArrow_Replace'
                print_changes(b, str1, str2, i-1, j-1)
                print(f'replace  {str2[j-1]}')

            elif b[i,j] == 2:               #'UpArrow'
                print_changes(b, str1, str2, i-1, j)
                print(f'omit     {str1[i-1]}')

            else:                           #'LeftArrow'
                print_changes(b, str1, str2, i, j-1)
                print(f'insert   {str2[j-1]}')

    print_changes(b, str1, str2, m, n)
            
    return c[m,n]

In [175]:
string_convert('bffflooo', 'buffalo')

match    b
replace  u
match    f
match    f
insert   a
match    l
omit     o
omit     o
match    o


4

In [169]:
string_convert('blder', 'boulder')

match    b
insert   o
insert   u
match    l
match    d
match    e
match    r


2

In [170]:
string_convert('blder', 'baller')

match    b
insert   a
match    l
replace  l
match    e
match    r


2

In [171]:
string_convert('blder', 'bold')

match    b
insert   o
match    l
match    d
omit     e
omit     r


3

In [181]:
string_convert('ACCGGTCGAGTGCGCGGAAGCCGGCCGAA', 'GTCGTTCGGAATGCCGTTGCTCTGTAAA')

replace  G
replace  T
match    C
match    G
replace  T
match    T
match    C
insert   G
match    G
match    A
replace  A
match    T
match    G
match    C
omit     G
match    C
match    G
replace  T
replace  T
omit     A
match    G
match    C
insert   T
match    C
replace  T
match    G
replace  T
replace  A
omit     G
match    A
match    A


14

# 0-1 Knapsack Problem

Ralphie has been declared the winner of a contest. She is given a choice of $n$ possible prizes. The $i$th prize is worth $v_i$ dollars and weighs $w_i$ pounds, where $v_i$ and $w_i$ are integers. Ralphie is given a bag to fill with as many prizes as she can carry away. If Ralphie wants to maximize the total value of her winnings and she can lift at most $W$ pounds, which prizes should she select?

In [ ]:
def knapsack(wgts, vals, max_wgt):
    '''Given weights and values for n items, along with a max weight,
       determine the max total value and corresponding weight'''
    
    n = len(wgts)
    
    # Initialize an (n+1) by (max_wgt+1) table to zeros. 
    # Row 0 and col 0 will remain zeros.    
    knapval = np.zeros((n+1, max_wgt+1), dtype=int)
    
    
    '''The max value you can get from 6 items with a max weight of 1 is the max value item that is 1 pound'''
    '''The max value you can get from 6 items with a max weight of 2 is the max value of any 2 1 pound items or 1
    2 pound item'''

    for i in range(1, n+1):
        for j in range(1, max_wgt+1):
            

In [6]:
np.zeros((10, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### LCS Helper Function

In [182]:
# def lcs(str1, str2):
#     m = len(str1)
#     n = len(str2)

#     # initialize matrices of the right sizes
#     zeros = [0]*(n+1)
#     c = np.array([zeros for _ in range(m+1)])
#     b = np.array([zeros for _ in range(m+1)])
    
#     # populate the two matrices
#     for i in range(1, m+1):
#         for j in range(1, n+1):
#             if str1[i-1] == str2[j-1]:
#                 c[i, j] = c[i-1,j-1] + 1
#                 b[i, j] = 3 #'NWArrow'
#             elif c[i-1,j] >= c[i,j-1]:
#                 c[i,j] = c[i-1,j]
#                 b[i,j] = 2 #'UpArrow'
#             else:
#                 c[i,j] = c[i,j-1]
#                 b[i,j] = 1 #'LeftArrow'
    
#     return form_lcs(b, str1, m, n)